@startuml
!include <C4/C4_Context>

Person(user, "Пользователь", "Владелец системы умного дома\n(Управление профилем, платежами,\nопрос датчиков)")

System_Boundary(c1, "Экосистема Умного дома") {
    System(users, "Users", "Предоставление профиля пользователя \nРегистрация новых пользователей")
    System(payment, "Payment","Управление платежами и подписками")
    System(tel, "Telemetry","Управление платежами и подписками")
}

Rel(user, c1, "Регистрация,\nУправление профилем,\nУправление подписками и платежами", "HTTPS")
@enduml